### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by AskAlice** [X-Ryl669/grav-affiliate-links#1]
when i installed it threw
```
The "/home/redacted/public_html/user/plugins/affiliate-links/templates" directory does not exist
```

there is also no directory for this in the git repo, suggesting there is some git-level issue here.

simply running `rm -rf /home/redacted/public_html/user/plugins/affiliate-links` fixed my issue, but also killed the plugin. Not investigating further.

**Comment by X-Ryl669** [comment]
You're right. It should be fixed now. Thanks for your report.
